### ISSUE TITLE
Need Help..!

### ISSUE THREAD

**Issue by kasunbhathiya** [Ashok93/occupancy-grid-mapping#1]
Hi could you please clarify for me which dataset type that we should use in these codes.. from these options --> [unsynced+unrectified data] , [synced+rectified data] , [calibration] , [tracklets]
Really sorry if this is a primitive question. I'm new to these subjects. !

**Comment by Ashok93** [comment]
@kasunbhathiya  Really sorry for the delayed response. Unfortunately, I am not maintaining this repository anymore, this was done as a part of my learning during my University courses. I hope the code could just serve as template for learning 🙏
