### ISSUE TITLE
why do we need the log probability in the update map function? 

### ISSUE THREAD

**Issue by AOOOOOA** [Ashok93/occupancy-grid-mapping#2]
https://github.com/Ashok93/occupancy-grid-mapping/blob/15df31c5d4e8840708689f0e89240725ef166570/occupancy_grid.py#L29

Hi, I'm reading your code but have a few questions. Why do we need to use the probability log_occupied or log_free here? 

If I want to increase the 2D grid map into the 3D grid map, can I directly add a dimension to the Class Map? I did so, but the result seems weird.

Thanks.

**Comment by Ashok93** [comment]
@AOOOOOA  Sorry for the delayed response. Unfortunately, I am not maintaining this repository anymore, this was done as a part of my learning during my University courses. I hope the code could serve as template for learning 🙏
